version: "3.2"
services:
  migrate:
    build: ..
    container_name: migrate
    volumes:
      - $ENV_FILE:/opt/vulcan0x/.env
      - ./wait-for:/opt/vulcan0x/wait-for
      - ./../src:/opt/vulcan0x/src
      - ./../config:/opt/vulcan0x/config
    command: >
      bash -c "ENV=/opt/vulcan0x/.env npm run migrate"
    restart: on-failure

  sync:
    build: ..
    container_name: sync
    volumes:
      - $ENV_FILE:/opt/vulcan0x/.env
      - ./wait-for:/opt/vulcan0x/wait-for
      - ./../src:/opt/vulcan0x/src
      - ./../config:/opt/vulcan0x/config
    command: >
      bash -c "ENV=/opt/vulcan0x/.env npm run sync"
    restart: always

  subscribe:
    build: ..
    container_name: subscribe
    volumes:
      - $ENV_FILE:/opt/vulcan0x/.env
      - ./wait-for:/opt/vulcan0x/wait-for
      - ./../src:/opt/vulcan0x/src
      - ./../config:/opt/vulcan0x/config
    command: >
      bash -c "ENV=/opt/vulcan0x/.env npm run subscribe"
    restart: always

  graphql:
    build: ..
    container_name: graphql
    ports:
      - 4000:4000
    volumes:
      - $ENV_FILE:/opt/vulcan0x/.env
      - ./wait-for:/opt/vulcan0x/wait-for
      - ./../graphql:/opt/vulcan0x/graphql
      - ./../config:/opt/vulcan0x/config
    command: >
      bash -c "ENV=/opt/vulcan0x/.env npm run graphql"
    restart: always
